In [ ]:
import numpy as np

In [ ]:
from time import process_time

# Time Taken

In [ ]:
list1 = [i for i in range(100000)]

start = process_time()

list1 = [i+5 for i in list1]

end = process_time()

print(end-start)

0.010162440000001993


In [ ]:
np_array1 = np.array([i for i in range(100000)])

start = process_time()

np_array1 += 5

end = process_time()

print(end-start)

0.0011711669999989738


# Test

In [ ]:
a = np.zeros((3,2))
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
b = np.ones((2,3), dtype=int)
print(b)

[[1 1 1]
 [1 1 1]]


In [ ]:
c = np.full((3,2), 5)
print(c)

[[5 5]
 [5 5]
 [5 5]]


In [ ]:
d = np.eye(4, dtype=int)
print(d)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
e = np.random.random((3,4))
print(e)

[[0.79334332 0.97381844 0.97371799 0.79514382]
 [0.30357265 0.72242245 0.6444487  0.52411843]
 [0.65672243 0.26084989 0.35269812 0.35169237]]


In [ ]:
f = np.array([[1,2,3,4],[5,6,7,8]])
print(f)
f.shape
f.dtype

[[1 2 3 4]
 [5 6 7 8]]


dtype('int64')

In [ ]:
g = np.random.randint(10,100,(4,5))
print(g)

[[53 76 41 74 93]
 [23 34 21 64 82]
 [52 33 82 98 23]
 [62 38 28 34 51]]


In [ ]:
h = np.linspace(10,30,5)
print(h)

[10. 15. 20. 25. 30.]


In [ ]:
i = np.arange(10,30,6)
print(i)

[10 16 22 28]


In [ ]:
list1 = [1,2,3,4,5]
j = np.array(list1)
print(j)

[1 2 3 4 5]


In [ ]:
k = np.random.randint(10,100,(3,2))
print(k)
l = np.transpose(k)
print(l)

[[80 81]
 [13 31]
 [33 55]]
[[80 13 33]
 [81 31 55]]


In [ ]:
m = np.random.randint(10,100,(3,2))
print(m)
n = m.T
print(n)

[[59 32]
 [26 37]
 [62 60]]
[[59 26 62]
 [32 37 60]]


In [ ]:
o = np.random.randint(10,100,(3,2))
print(o)
p = o.reshape((2,3))
print(p)
p.shape

[[35 80]
 [31 58]
 [43 16]]
[[35 80 31]
 [58 43 16]]


(2, 3)

# Mathematical Operations

In [ ]:
q = np.random.randint(10,100,(3,3))
r = np.random.randint(10,100,(3,3))
print(q)
print(r)

[[34 89 15]
 [91 17 64]
 [83 47 76]]
[[76 47 28]
 [39 84 48]
 [44 55 45]]


In [ ]:
print(q+r)
print(q-r)
print(q*r)
print(q/r)

[[110 136  43]
 [130 101 112]
 [127 102 121]]
[[-42  42 -13]
 [ 52 -67  16]
 [ 39  -8  31]]
[[2584 4183  420]
 [3549 1428 3072]
 [3652 2585 3420]]
[[0.44736842 1.89361702 0.53571429]
 [2.33333333 0.20238095 1.33333333]
 [1.88636364 0.85454545 1.68888889]]


In [ ]:
print(np.add(q,r))
print(np.subtract(q,r))
print(np.multiply(q,r))
print(np.divide(q,r))