In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
crop = pd.read_csv('/content/Crop_recommendation.csv')

In [3]:
crop.head()

N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [4]:
crop.isnull().sum()

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [6]:
crop.duplicated().sum()

0

In [7]:
crop['label'].unique()

array(['rice', 'maize', 'chickpea', 'kidneybeans', 'pigeonpeas',
       'mothbeans', 'mungbean', 'blackgram', 'lentil', 'pomegranate',
       'banana', 'mango', 'grapes', 'watermelon', 'muskmelon', 'apple',
       'orange', 'papaya', 'coconut', 'cotton', 'jute', 'coffee'],
      dtype=object)

In [8]:
crop_dict = {
    'rice':1,
    'maize':2,
    'chickpea':3,
    'kidneybeans':4,
    'pigeonpeas':5,
    'mothbeans':6,
    'mungbean':7,
    'blackgram':8,
    'lentil':9,
    'pomegranate':10,
    'banana':11,
    'mango':12,
    'grapes':13,
    'watermelon':14,
    'muskmelon':15,
    'apple':16,
    'orange':17,
    'papaya':18,
    'coconut':19,
    'cotton':20,
    'jute':21,
    'coffee':22
}

In [9]:
crop['label'] = crop['label'].map(crop_dict)

In [10]:
crop.head()

N   P   K  temperature   humidity        ph    rainfall  label
0  90  42  43    20.879744  82.002744  6.502985  202.935536      1
1  85  58  41    21.770462  80.319644  7.038096  226.655537      1
2  60  55  44    23.004459  82.320763  7.840207  263.964248      1
3  74  35  40    26.491096  80.158363  6.980401  242.864034      1
4  78  42  42    20.130175  81.604873  7.628473  262.717340      1

In [13]:
X = crop.drop('label', axis=1)
y = crop['label']

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [11]:
from sklearn.preprocessing import MinMaxScaler

In [16]:
mx = MinMaxScaler()
mx.fit(X_train)
X_train = mx.transform(X_train)
X_test = mx.transform(X_test)

In [17]:
print(X_train)

[[0.12142857 0.07857143 0.045      ... 0.9089898  0.48532225 0.29685161]
 [0.26428571 0.52857143 0.07       ... 0.64257946 0.56594073 0.17630752]
 [0.05       0.48571429 0.1        ... 0.57005802 0.58835229 0.08931844]
 ...
 [0.07857143 0.22142857 0.13       ... 0.43760347 0.46198144 0.28719815]
 [0.07857143 0.85       0.995      ... 0.76763665 0.44420505 0.18346657]
 [0.22857143 0.52142857 0.085      ... 0.56099735 0.54465022 0.11879596]]


In [18]:
from sklearn.preprocessing import StandardScaler

In [19]:
sc = StandardScaler()
sc.fit(X_train)
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

In [20]:
print(X_train)

[[-9.03426596e-01 -1.12616170e+00 -6.68506601e-01 ...  9.36586183e-01
   1.93473784e-01  5.14970176e-03]
 [-3.67051340e-01  7.70358846e-01 -5.70589522e-01 ... -1.00470485e-01
   8.63917548e-01 -6.05290566e-01]
 [-1.17161422e+00  5.89737842e-01 -4.53089028e-01 ... -3.82774991e-01
   1.05029771e+00 -1.04580687e+00]
 ...
 [-1.06433917e+00 -5.24091685e-01 -3.35588533e-01 ... -8.98381379e-01
  -6.34357580e-04 -4.37358211e-02]
 [-1.06433917e+00  2.12501638e+00  3.05234239e+00 ...  3.86340190e-01
  -1.48467347e-01 -5.69036842e-01]
 [-5.01145154e-01  7.40255346e-01 -5.11839275e-01 ... -4.18045489e-01
   6.86860180e-01 -8.96531475e-01]]


In [21]:
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

In [22]:
models = {
    'Random Forest': RandomForestClassifier(),
    'Extra Trees': ExtraTreesClassifier(),
    'Decision Tree': DecisionTreeClassifier(),
    'K-Nearest Neighbors': KNeighborsClassifier(),
    'Support Vector Machine': SVC(),
    'Naive Bayes': GaussianNB()
}

In [23]:
for name, model in models.items():
  model.fit(X_train, y_train)
  y_pred = model.predict(X_test)
  accuracy = accuracy_score(y_test, y_pred)
  print(f'{name} Accuracy: {accuracy}')

Random Forest Accuracy: 0.9931818181818182
Extra Trees Accuracy: 0.9863636363636363
Decision Tree Accuracy: 0.9818181818181818
K-Nearest Neighbors Accuracy: 0.9659090909090909
Support Vector Machine Accuracy: 0.9681818181818181
Naive Bayes Accuracy: 0.9954545454545455


In [24]:
model = GaussianNB()
model.fit(X_train, y_train)

GaussianNB()

In [25]:
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

Accuracy: 0.9954545454545455


In [32]:
input = [90,42,43,20.879744,	82.002744,	6.502985,	202.935536]
input = np.array(input)
input = input.reshape(1, -1)
input = mx.transform(input)
input = sc.transform(input)
prediction = model.predict(input)
print(prediction)

[1]


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


In [33]:
import pickle

In [34]:
# prompt: Save model using pickle

# Save the model
filename = 'trained_model.sav'
pickle.dump(model, open(filename, 'wb'))
